In [ ]:
import numpy as np

x = np.arange(5)
y = np.arange(4)

X, Y = np.meshgrid(x, y, indexing='ij')
print("X:\n", X)
print("Y:\n", Y)


X:
 [[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
Y:
 [[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
