In [13]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6]])

rows = 2
columns = 3

row_index = 5 * np.arange(rows)
column_index = 5 * np.arange(columns)
print(row_index)
print(column_index)

zoom_in_image_array = np.zeros((rows * 5, columns * 5))
zoom_in_image_array[row_index[:, np.newaxis], column_index] = array
print(zoom_in_image_array)


[0 5]
[ 0  5 10]
[[1. 0. 0. 0. 0. 2. 0. 0. 0. 0. 3. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0. 5. 0. 0. 0. 0. 6. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [3]:
import tkinter as tk
from tkinter import ttk
from tkinter import filedialog as fd
from PIL import Image
from PIL import ImageTk
import numpy as np
from matplotlib import pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2Tk
from matplotlib.figure import Figure
import struct

def bilinear_interpolation (x1, y1, x2, y2, 
                            value11, value12, value21, value22, 
                            x, y):
    coef = 1 / ((x2 - x1) * (y2 - y1))
    vector1 = np.array([x2 - x, x - x1])
    matrix = np.array([[value11, value12], [value21, value22]])
    vector2 = np.array([[y2 - y], [y - y1]])
    result = coef * (vector1 @ matrix @ vector2)  # 使用@符号进行矩阵运算
    return result[0]

def bilinear_interpolation_2 (x1, y1, x2, y2, 
                            value11, value12, value21, value22, 
                            x, y):
    coef = 1 / ((x2 - x1) * (y2 - y1))
    result = coef * (value11 * (x2 - x) * (y2 - y) + 
                     value21 * (x - x1) * (y2 - y) + 
                     value12 * (x2 - x) * (y - y1) + 
                     value22 * (x - x1) * (y - y1))
    
    return result

print(bilinear_interpolation(1, 2, 10, 14, 5, 9, 7, 8, 2, 10))
print(bilinear_interpolation_2(1, 2, 10, 14, 5, 9, 7, 8, 2, 10))

7.666666666666666
7.666666666666666
